# on:
#   push:
#     branches:
#       - master

# name: Release
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     name: Check Tests
#     steps:
#       - uses: actions/checkout@v1
#       - name: Setup Node.js for use with actions
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - run: npm test

#   action:
#     needs: test
#     runs-on: ubuntu-latest
#     name: Publish GitHub Action
#     steps:
#       - uses: actions/checkout@v1
#       - name: Setup Node.js for use with actions
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - run: npm run build
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           push_options: '--force'
#           file_pattern: dist/**/*.js

name: Autopublish to npm when release created
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@example.com"
      - run: npm version ${{ github.event.release.tag_name }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # push the version changes to GitHub
      - run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
